# Source Prezto.
if [[ -s "$HOME/.dotfiles/shells/modules/prezto/init.zsh" ]]; then
  source "$HOME/.dotfiles/shells/modules/prezto/init.zsh"
fi

# Customize to your needs...

# Aliases
source "$HOME/.dotfiles/shells/aliases/general"

# Common things
source "$HOME/.dotfiles/shells/common.sh"

# COLORS! YAY!
export LSCOLORS="GxfxcxdxbxGxDxabagacad"

# Bindings
# vi
# bindkey -v

# emacs
bindkey -e

# ctl + arrow keys
bindkey ";5D" backward-word
bindkey ";5C" forward-word

# alt + arrow keys
bindkey ";3D" beginning-of-line
bindkey ";3C" end-of-line
