set nocompatible
set encoding=utf-8
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'myusuf3/numbers.vim'
Bundle 'Shougo/neocomplcache.vim'
Bundle 'kein/ctrlp.vim'
Bundle 'godlygeek/tabular'
Bundle 'chriskempson/tomorrow-theme', { "rtp": "vim/" }
"Bundle 'mattn/emmet-vim'
Bundle 'rstacruz/sparkup', { "rtp": "vim/" }
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-fugitive'
Bundle 'Lokaltog/vim-easymotion'

filetype plugin indent on
syntax on

" Enable mouse
set mouse=a

" Whitespace
set listchars=eol:$,tab:>-,trail:*,extends:>,precedes:<
set list

" Remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" Colour scheme
set t_Co=256
colorscheme Tomorrow-Night

" NeoComplCache
let g:neocomplcache_enable_at_startup=1

" NERDTree
map <C-d> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
map <C-n> :NERDTreeMirror<CR>

" Line numbers
set number
let g:enable_numbers = 0

" Tabs
map <C-t><Left> :tabp<cr>
map <C-t><Right> :tabn<cr>
