# Source Prezto.
if [[ -s "$HOME/.dotfiles/zsh/prezto/init.zsh" ]]; then
  source "$HOME/.dotfiles/zsh/prezto/init.zsh"
fi

# Customize to your needs...

# Aliases
source "$HOME/.dotfiles/aliases/general"

# Common things
source "$HOME/.dotfiles/common.sh"

# COLORS! YAY!
export LSCOLORS="GxfxcxdxbxGxDxabagacad"

# Bindings
# vi
bindkey -v

# emacs
# bindkey -e

# ctl + arrow keys
# bindkey ";5D" backward-word
# bindkey ";5C" forward-word

# alt + arrow keys
# bindkey ";3D" beginning-of-line
# bindkey ";3C" end-of-line
