# Source Prezto.
#if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
#  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
#fi

if [[ -s "$HOME/.dotfiles/zsh/prezto/init.zsh" ]]; then
  source "$HOME/.dotfiles/zsh/prezto/init.zsh"
fi

# Customize to your needs...

# rbenv <3
export SSL_CERT_FILE="`brew --prefix curl-ca-bundle`/share/ca-bundle.crt"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"

# Load z
#source ~/.dotfiles/modules/z/z.sh

# Load fasd
alias fasd="$HOME/.dotfiles/modules/fasd/fasd"
eval "$(fasd --init auto)"

source "$HOME/.dotfiles/aliases"

# COLORS! YAY!
export LSCOLORS="GxfxcxdxbxGxDxabagacad"
