#!/usr/bin/env bash

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Path to the bash it configuration
export BASH_IT=$HOME/.dotfiles/bash/bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='wat'

# Load Bash It
source $BASH_IT/bash_it.sh

# rbenv
if [[ ! `which rbenv` ]]
  then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

alias fasd="$HOME/.dotfiles/modules/fasd/fasd"
eval "$(fasd --init auto)"

source "$HOME/.dotfiles/aliases"
