#!/usr/bin/env bash

if [ "$(uname)" = "Darwin" ]; then
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
fi

# Path to the bash it configuration
export BASH_IT=$HOME/.dotfiles/bash/bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='wat'

# Load Bash It
source $BASH_IT/bash_it.sh

# Common things
source "$HOME/.dotfiles/common.sh"
